- hosts: servers
  remote_user: root
  tasks:
  
  - lineinfile:
      path: /etc/resolv.conf
      regexp: 'nameserver'
      line: 'nameserver 10.22.2.10'

  - lineinfile:
      path: /etc/resolv.conf
      regexp: 'search'
      line: 'search wcbc.local'
